name: agent
persist_directory: rag
chunk_size: 200
chunk_overlap: 20
separators: ["\n\n","\n",".","!","?",",","，","。","？","！"," "," ",""]
k: 3


md5_hex_store : md5.text
allowed_files_type: ['txt', 'pdf']
data_path: data